### PR TITLE
Update LineChart when the columns prop changes.

### PR DESCRIPTION
**Pull request by jdugan1024**
I'd like to add this and bump to 0.9.1. Seem ok?

### CODE REVIEW

**Comment by pjm17971** [comment]
+1

**Comment by pjm17971** [comment]
@jdugan: I think this needs to be merged into master and a patch release made.

**Comment by jdugan** [comment]
I think you meant to address @jdugan1024. :)

**Comment by pjm17971** [comment]
@jdugan Wow that autocomplete is pretty global. Sorry about that. But if you ever wanted to work on a charts library, we could use all the jdugans we can get.

**Pull request merged**
