### PR TITLE
Show negative values in BarChart

### LINKED ISSUE #94: Negative values are not shown in BarChart
First, thanks for putting this library on github. Happy there is a charting library that takes time series seriously and does not add it as an afterthought! 

I have a bar chart that has negative values, which are not shown. Most of the other charts, e.g. AreaChart show negative values. Looks like change would be very minimal. Modified it for my own use and will issue it as a PR.

### PR DESCRIPTION
**Pull request by jverhoeven**
Also, keep minimum bar height of 1 pixel (although this can be questioned).

Fixes #94.

Regarding following the guidelines: I did not make an example as adding a negative value to the existing traffic charts is not logical. If this is an issue, please instruct me where to put an example in the website.

### CODE REVIEW

**Comment by pjm17971** [comment]
Thanks for the PR!

That's cool to support. I'm wondering what happens now if you mix negative and positive values, since multiple columns stack on top of each other. I'm thinking the right thing to do is to stack negative values down and position values up. In the code, I guess that means maintaining two versions of `ypos` and separately rendering the two directions. Thoughts?

For examples, it would be nice to add one, especially if you want to take a shot at the above. You can just add it to the bottom of the current barchart graph and make up some data, or use something realistic if you have it and can share.

**Comment by jverhoeven** [comment]
Good one. Did not test stacked bars. I am a afraid no matter how you implement them, it will look awkward. I will give your 2 ypos suggestion a try and see how it looks. Will get back to you.

**Comment by pjm17971** [comment]
Here's an example with highcharts, so I think the two directions of stacking are the way to go:

screen shot 2016-11-01 at 10 09 34 am

This would actually be quite useful, because we do have in and out traffic and they could be shown opposed to each other in the same way we can do with the area charts.

**Comment by jverhoeven** [comment]
Updated my PR. Please check. Added another bar chart example to the volumes page. Tried to use your dataset creating 'net traffic' values from the 'in' and 'out' columns. I had some trouble finding sites with similar net traffic values. I think it works to demonstrate the concept.

**Pull request merged**
