### PR TITLE
Styler: Use color scheme fallback on Line|Bar|Scatter Charts too.

### LINKED ISSUE #102: [bug] Styler <scatter|bar|line>ChartStyle() don't use the color scheme as fallback color
styler's functions below,don't use as fallback, the color scheme of the styler :
+ ``` scatterChartStyle() ```
+ ``` barChartStyle() ```
+ ``` lineChartStyle() ```

> + ``` axisStyle() ```
>  + ``` areaChartStyle() ```
> + ``` legendStyle() ``` 
> are ok though

### PR DESCRIPTION
**Pull request by siavelis**
Color scheme fallback by Styler was not used on components:
+ LineChart
+ BarChart
+ ScatterChart

but, was used on:
+ Legend
+ Axis
+ AreaChart

Fixes #102

### CODE REVIEW

**Comment by siavelis** [comment]
Also, added packages:
+ webpack
+ react-dom
in the devDependencies.

(I couldn't find out why babel changed multiple vars to comma separated expressions)

**Comment by pjm17971** [comment]
Awesome, thanks for this. Looks great (well except for the babel explosion, I guess the version probably changed). One question, I'm wondering why webpack is necessary as that should be managed by react-scripts?

**Comment by siavelis** [comment]
I've just add it because npm said it had an unmet peer dependency. I can remove it, if it is not needed.

**Comment by pjm17971** [comment]
I'll merge it and then take a look at the dependencies. They don't hurt, but I'm curious (and it hasn't been an issue for us so far). I'm also considering moving the project to yarn so that there's less thrashing on versions (like babel) between developers. Anyway, thanks for the pull request!!

**Pull request merged**
